# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tipLocatorUIBase.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TipLocator(object):
    def setupUi(self, TipLocator):
        TipLocator.setObjectName("TipLocator")
        TipLocator.resize(700, 500)
        TipLocator.setMinimumSize(QtCore.QSize(700, 500))
        TipLocator.setMaximumSize(QtCore.QSize(700, 500))
        self.labelStageControl = QtWidgets.QLabel(TipLocator)
        self.labelStageControl.setGeometry(QtCore.QRect(130, 100, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelStageControl.setFont(font)
        self.labelStageControl.setObjectName("labelStageControl")
        self.buttonMovementAbort = QtWidgets.QPushButton(TipLocator)
        self.buttonMovementAbort.setGeometry(QtCore.QRect(270, 140, 71, 71))
        self.buttonMovementAbort.setObjectName("buttonMovementAbort")
        self.entryBoxDirection_Y = QtWidgets.QLineEdit(TipLocator)
        self.entryBoxDirection_Y.setGeometry(QtCore.QRect(150, 240, 41, 21))
        self.entryBoxDirection_Y.setObjectName("entryBoxDirection_Y")
        self.buttonDirectionNeg_X = QtWidgets.QPushButton(TipLocator)
        self.buttonDirectionNeg_X.setGeometry(QtCore.QRect(90, 180, 40, 40))
        self.buttonDirectionNeg_X.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonDirectionNeg_X.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonDirectionNeg_X.setObjectName("buttonDirectionNeg_X")
        self.entryBoxDirection_X = QtWidgets.QLineEdit(TipLocator)
        self.entryBoxDirection_X.setGeometry(QtCore.QRect(90, 240, 41, 21))
        self.entryBoxDirection_X.setObjectName("entryBoxDirection_X")
        self.buttonDirectionPos_Y = QtWidgets.QPushButton(TipLocator)
        self.buttonDirectionPos_Y.setGeometry(QtCore.QRect(150, 130, 40, 40))
        self.buttonDirectionPos_Y.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonDirectionPos_Y.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonDirectionPos_Y.setObjectName("buttonDirectionPos_Y")
        self.labelMovementDistance = QtWidgets.QLabel(TipLocator)
        self.labelMovementDistance.setGeometry(QtCore.QRect(20, 242, 60, 21))
        self.labelMovementDistance.setMinimumSize(QtCore.QSize(60, 21))
        self.labelMovementDistance.setMaximumSize(QtCore.QSize(60, 21))
        self.labelMovementDistance.setObjectName("labelMovementDistance")
        self.buttonDirectionPos_X = QtWidgets.QPushButton(TipLocator)
        self.buttonDirectionPos_X.setGeometry(QtCore.QRect(90, 130, 40, 40))
        self.buttonDirectionPos_X.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonDirectionPos_X.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonDirectionPos_X.setObjectName("buttonDirectionPos_X")
        self.entryBoxDirection_Z = QtWidgets.QLineEdit(TipLocator)
        self.entryBoxDirection_Z.setGeometry(QtCore.QRect(210, 240, 41, 21))
        self.entryBoxDirection_Z.setObjectName("entryBoxDirection_Z")
        self.buttonDirectionPos_Z = QtWidgets.QPushButton(TipLocator)
        self.buttonDirectionPos_Z.setGeometry(QtCore.QRect(210, 130, 40, 40))
        self.buttonDirectionPos_Z.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonDirectionPos_Z.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonDirectionPos_Z.setObjectName("buttonDirectionPos_Z")
        self.buttonDirectionNeg_Z = QtWidgets.QPushButton(TipLocator)
        self.buttonDirectionNeg_Z.setGeometry(QtCore.QRect(210, 180, 40, 40))
        self.buttonDirectionNeg_Z.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonDirectionNeg_Z.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonDirectionNeg_Z.setObjectName("buttonDirectionNeg_Z")
        self.labelMovementDirection = QtWidgets.QLabel(TipLocator)
        self.labelMovementDirection.setGeometry(QtCore.QRect(20, 170, 60, 21))
        self.labelMovementDirection.setMinimumSize(QtCore.QSize(60, 21))
        self.labelMovementDirection.setMaximumSize(QtCore.QSize(60, 21))
        self.labelMovementDirection.setObjectName("labelMovementDirection")
        self.buttonDirectionNeg_Y = QtWidgets.QPushButton(TipLocator)
        self.buttonDirectionNeg_Y.setGeometry(QtCore.QRect(150, 180, 40, 40))
        self.buttonDirectionNeg_Y.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonDirectionNeg_Y.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonDirectionNeg_Y.setObjectName("buttonDirectionNeg_Y")
        self.lineTipLocatorStageControl = QtWidgets.QFrame(TipLocator)
        self.lineTipLocatorStageControl.setGeometry(QtCore.QRect(10, 80, 341, 16))
        self.lineTipLocatorStageControl.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineTipLocatorStageControl.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineTipLocatorStageControl.setObjectName("lineTipLocatorStageControl")
        self.labelTIpLocator = QtWidgets.QLabel(TipLocator)
        self.labelTIpLocator.setGeometry(QtCore.QRect(140, 10, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelTIpLocator.setFont(font)
        self.labelTIpLocator.setObjectName("labelTIpLocator")
        self.buttonTipLocatorInitialPositon = QtWidgets.QPushButton(TipLocator)
        self.buttonTipLocatorInitialPositon.setGeometry(QtCore.QRect(20, 30, 110, 41))
        self.buttonTipLocatorInitialPositon.setObjectName("buttonTipLocatorInitialPositon")
        self.buttonTipLocatorStartRoutine = QtWidgets.QPushButton(TipLocator)
        self.buttonTipLocatorStartRoutine.setGeometry(QtCore.QRect(130, 30, 110, 41))
        self.buttonTipLocatorStartRoutine.setObjectName("buttonTipLocatorStartRoutine")
        self.buttonTipLocatorAbortRoutine = QtWidgets.QPushButton(TipLocator)
        self.buttonTipLocatorAbortRoutine.setGeometry(QtCore.QRect(240, 30, 110, 41))
        self.buttonTipLocatorAbortRoutine.setObjectName("buttonTipLocatorAbortRoutine")
        self.buttonQuit = QtWidgets.QPushButton(TipLocator)
        self.buttonQuit.setGeometry(QtCore.QRect(29, 441, 111, 51))
        self.buttonQuit.setObjectName("buttonQuit")

        self.retranslateUi(TipLocator)
        QtCore.QMetaObject.connectSlotsByName(TipLocator)
        TipLocator.setTabOrder(self.entryBoxDirection_X, self.entryBoxDirection_Y)
        TipLocator.setTabOrder(self.entryBoxDirection_Y, self.entryBoxDirection_Z)
        TipLocator.setTabOrder(self.entryBoxDirection_Z, self.buttonTipLocatorInitialPositon)
        TipLocator.setTabOrder(self.buttonTipLocatorInitialPositon, self.buttonTipLocatorStartRoutine)
        TipLocator.setTabOrder(self.buttonTipLocatorStartRoutine, self.buttonTipLocatorAbortRoutine)
        TipLocator.setTabOrder(self.buttonTipLocatorAbortRoutine, self.buttonDirectionPos_X)
        TipLocator.setTabOrder(self.buttonDirectionPos_X, self.buttonDirectionNeg_X)
        TipLocator.setTabOrder(self.buttonDirectionNeg_X, self.buttonDirectionPos_Y)
        TipLocator.setTabOrder(self.buttonDirectionPos_Y, self.buttonDirectionNeg_Y)
        TipLocator.setTabOrder(self.buttonDirectionNeg_Y, self.buttonDirectionPos_Z)
        TipLocator.setTabOrder(self.buttonDirectionPos_Z, self.buttonDirectionNeg_Z)
        TipLocator.setTabOrder(self.buttonDirectionNeg_Z, self.buttonMovementAbort)

    def retranslateUi(self, TipLocator):
        _translate = QtCore.QCoreApplication.translate
        TipLocator.setWindowTitle(_translate("TipLocator", "Tip Locator"))
        self.labelStageControl.setText(_translate("TipLocator", "Stage Control"))
        self.buttonMovementAbort.setText(_translate("TipLocator", "Abort"))
        self.entryBoxDirection_Y.setText(_translate("TipLocator", "0"))
        self.buttonDirectionNeg_X.setText(_translate("TipLocator", "-X"))
        self.entryBoxDirection_X.setText(_translate("TipLocator", "0"))
        self.buttonDirectionPos_Y.setText(_translate("TipLocator", "+Y"))
        self.labelMovementDistance.setText(_translate("TipLocator", "Distance:"))
        self.buttonDirectionPos_X.setText(_translate("TipLocator", "+X"))
        self.entryBoxDirection_Z.setText(_translate("TipLocator", "0"))
        self.buttonDirectionPos_Z.setText(_translate("TipLocator", "+Z"))
        self.buttonDirectionNeg_Z.setText(_translate("TipLocator", "-Z"))
        self.labelMovementDirection.setText(_translate("TipLocator", "Direction:"))
        self.buttonDirectionNeg_Y.setText(_translate("TipLocator", "-Y"))
        self.labelTIpLocator.setText(_translate("TipLocator", "Tip Locator"))
        self.buttonTipLocatorInitialPositon.setText(_translate("TipLocator", "Initial Position"))
        self.buttonTipLocatorStartRoutine.setText(_translate("TipLocator", "Start Routine"))
        self.buttonTipLocatorAbortRoutine.setText(_translate("TipLocator", "Abort Routine"))
        self.buttonQuit.setText(_translate("TipLocator", "Quit"))

